//! Auto-generated PyPI skip list
//! DO NOT EDIT - Generated by scripts/gen_packages.py
//!
//! Packages with native Zig implementations.
//! Package manager skips downloading these from PyPI.

const std = @import("std");

/// PyPI packages with native implementations
pub const native_packages = [_][]const u8{
    "requests",
    "httpx",
    "urllib3",
    "aiohttp",
    "regex",
    "ujson",
    "orjson",
    "simplejson",
    "tiktoken",
    "tokenizers",
    "websockets",
    "websocket-client",
};

/// Check if package has native implementation
pub fn hasNativeImpl(name: []const u8) bool {
    for (native_packages) |pkg| {
        if (std.ascii.eqlIgnoreCase(name, pkg)) return true;
    }
    return false;
}
