/**
 * TypeScript definitions for hello WASM module
 * Auto-generated by metal0
 *
 * Usage:
 *   import { load } from '@metal0/wasm-runtime';
 *   import type { Module } from './hello';
 *   const mod = await load<Module>('./hello.wasm');
 */

export interface Module {
  main(): void;
}
