//! Pickle protocol opcode definitions and metadata.
//!
//! Defines all pickle opcodes from protocols 0-5 with metadata methods.
//! Mirrors: CPython Lib/pickletools.py - opcode definitions

const std = @import("std");

/// Pickle protocol opcodes
pub const Opcode = enum(u8) {
    // Protocol 0/1 (ASCII)
    MARK = '(',
    STOP = '.',
    POP = '0',
    POP_MARK = '1',
    DUP = '2',
    FLOAT = 'F',
    INT = 'I',
    BININT = 'J',
    BININT1 = 'K',
    LONG = 'L',
    BININT2 = 'M',
    NONE = 'N',
    PERSID = 'P',
    BINPERSID = 'Q',
    REDUCE = 'R',
    STRING = 'S',
    BINSTRING = 'T',
    SHORT_BINSTRING = 'U',
    UNICODE = 'V',
    BINUNICODE = 'X',
    APPEND = 'a',
    BUILD = 'b',
    GLOBAL = 'c',
    DICT = 'd',
    EMPTY_DICT = '}',
    APPENDS = 'e',
    GET = 'g',
    BINGET = 'h',
    INST = 'i',
    LONG_BINGET = 'j',
    LIST = 'l',
    EMPTY_LIST = ']',
    OBJ = 'o',
    PUT = 'p',
    BINPUT = 'q',
    LONG_BINPUT = 'r',
    SETITEM = 's',
    TUPLE = 't',
    EMPTY_TUPLE = ')',
    SETITEMS = 'u',
    BINFLOAT = 'G',

    // Protocol 2
    PROTO = 0x80,
    NEWOBJ = 0x81,
    EXT1 = 0x82,
    EXT2 = 0x83,
    EXT4 = 0x84,
    TUPLE1 = 0x85,
    TUPLE2 = 0x86,
    TUPLE3 = 0x87,
    NEWTRUE = 0x88,
    NEWFALSE = 0x89,
    LONG1 = 0x8a,
    LONG4 = 0x8b,

    // Protocol 3
    BINBYTES = 'B',
    SHORT_BINBYTES = 'C',

    // Protocol 4
    SHORT_BINUNICODE = 0x8c,
    BINUNICODE8 = 0x8d,
    BINBYTES8 = 0x8e,
    EMPTY_SET = 0x8f,
    ADDITEMS = 0x90,
    FROZENSET = 0x91,
    NEWOBJ_EX = 0x92,
    STACK_GLOBAL = 0x93,
    MEMOIZE = 0x94,
    FRAME = 0x95,

    // Protocol 5
    BYTEARRAY8 = 0x96,
    NEXT_BUFFER = 0x97,
    READONLY_BUFFER = 0x98,

    _,

    pub fn name(self: Opcode) []const u8 {
        return switch (self) {
            .MARK => "MARK",
            .STOP => "STOP",
            .POP => "POP",
            .POP_MARK => "POP_MARK",
            .DUP => "DUP",
            .FLOAT => "FLOAT",
            .INT => "INT",
            .BININT => "BININT",
            .BININT1 => "BININT1",
            .LONG => "LONG",
            .BININT2 => "BININT2",
            .NONE => "NONE",
            .PERSID => "PERSID",
            .BINPERSID => "BINPERSID",
            .REDUCE => "REDUCE",
            .STRING => "STRING",
            .BINSTRING => "BINSTRING",
            .SHORT_BINSTRING => "SHORT_BINSTRING",
            .UNICODE => "UNICODE",
            .BINUNICODE => "BINUNICODE",
            .APPEND => "APPEND",
            .BUILD => "BUILD",
            .GLOBAL => "GLOBAL",
            .DICT => "DICT",
            .EMPTY_DICT => "EMPTY_DICT",
            .APPENDS => "APPENDS",
            .GET => "GET",
            .BINGET => "BINGET",
            .INST => "INST",
            .LONG_BINGET => "LONG_BINGET",
            .LIST => "LIST",
            .EMPTY_LIST => "EMPTY_LIST",
            .OBJ => "OBJ",
            .PUT => "PUT",
            .BINPUT => "BINPUT",
            .LONG_BINPUT => "LONG_BINPUT",
            .SETITEM => "SETITEM",
            .TUPLE => "TUPLE",
            .EMPTY_TUPLE => "EMPTY_TUPLE",
            .SETITEMS => "SETITEMS",
            .BINFLOAT => "BINFLOAT",
            .PROTO => "PROTO",
            .NEWOBJ => "NEWOBJ",
            .EXT1 => "EXT1",
            .EXT2 => "EXT2",
            .EXT4 => "EXT4",
            .TUPLE1 => "TUPLE1",
            .TUPLE2 => "TUPLE2",
            .TUPLE3 => "TUPLE3",
            .NEWTRUE => "NEWTRUE",
            .NEWFALSE => "NEWFALSE",
            .LONG1 => "LONG1",
            .LONG4 => "LONG4",
            .BINBYTES => "BINBYTES",
            .SHORT_BINBYTES => "SHORT_BINBYTES",
            .SHORT_BINUNICODE => "SHORT_BINUNICODE",
            .BINUNICODE8 => "BINUNICODE8",
            .BINBYTES8 => "BINBYTES8",
            .EMPTY_SET => "EMPTY_SET",
            .ADDITEMS => "ADDITEMS",
            .FROZENSET => "FROZENSET",
            .NEWOBJ_EX => "NEWOBJ_EX",
            .STACK_GLOBAL => "STACK_GLOBAL",
            .MEMOIZE => "MEMOIZE",
            .FRAME => "FRAME",
            .BYTEARRAY8 => "BYTEARRAY8",
            .NEXT_BUFFER => "NEXT_BUFFER",
            .READONLY_BUFFER => "READONLY_BUFFER",
            else => "UNKNOWN",
        };
    }

    pub fn doc(self: Opcode) []const u8 {
        return switch (self) {
            .MARK => "Push markobject onto the stack.",
            .STOP => "Stop the unpickling machine.",
            .POP => "Pop the top of the stack, discarding it.",
            .NONE => "Push None on the stack.",
            .NEWTRUE => "Push True on the stack.",
            .NEWFALSE => "Push False on the stack.",
            .INT => "Push an integer.",
            .BININT => "Push a 4-byte signed integer.",
            .BININT1 => "Push a 1-byte unsigned integer.",
            .BININT2 => "Push a 2-byte unsigned integer.",
            .FLOAT => "Push a float.",
            .BINFLOAT => "Push an 8-byte IEEE float.",
            .STRING => "Push a string.",
            .BINSTRING => "Push a counted string.",
            .SHORT_BINSTRING => "Push a short counted string.",
            .UNICODE => "Push a Unicode string.",
            .BINUNICODE => "Push a counted Unicode string.",
            .BINBYTES => "Push a counted bytes object.",
            .SHORT_BINBYTES => "Push a short counted bytes object.",
            .EMPTY_LIST => "Push an empty list.",
            .EMPTY_TUPLE => "Push an empty tuple.",
            .EMPTY_DICT => "Push an empty dict.",
            .EMPTY_SET => "Push an empty set.",
            .LIST => "Build a list from topmost stack items.",
            .TUPLE => "Build a tuple from topmost stack items.",
            .DICT => "Build a dict from stack items.",
            .APPEND => "Append an object to a list.",
            .APPENDS => "Extend a list by a slice of stack objects.",
            .SETITEM => "Add a key+value pair to a dict.",
            .SETITEMS => "Add key+value pairs to a dict.",
            .PROTO => "Protocol version indicator.",
            .FRAME => "Start a new frame.",
            else => "No documentation available.",
        };
    }

    pub fn protocol(self: Opcode) u8 {
        return switch (self) {
            .PROTO, .NEWOBJ, .EXT1, .EXT2, .EXT4, .TUPLE1, .TUPLE2, .TUPLE3, .NEWTRUE, .NEWFALSE, .LONG1, .LONG4 => 2,
            .BINBYTES, .SHORT_BINBYTES => 3,
            .SHORT_BINUNICODE, .BINUNICODE8, .BINBYTES8, .EMPTY_SET, .ADDITEMS, .FROZENSET, .NEWOBJ_EX, .STACK_GLOBAL, .MEMOIZE, .FRAME => 4,
            .BYTEARRAY8, .NEXT_BUFFER, .READONLY_BUFFER => 5,
            else => 0,
        };
    }
};
