//! CPython source: Lib/encodings/cp852.py
//!
//! DOS Latin-2 (Central European) codepage
//!
//! Mirrors: CPython Lib/encodings/cp852.py

const std = @import("std");
const charmap = @import("charmap.zig");

pub const name = "cp852";
pub const aliases = [_][]const u8{ "ibm852", "852" };

const UNDEF = charmap.UNDEFINED;

/// CP852 decode table
const decode_table: [256]u21 = blk: {
    var table: [256]u21 = undefined;
    // 0x00-0x7F same as ASCII
    for (0..0x80) |i| table[i] = @intCast(i);
    // 0x80-0x9F
    table[0x80] = 0x00C7; // LATIN CAPITAL LETTER C WITH CEDILLA
    table[0x81] = 0x00FC; // LATIN SMALL LETTER U WITH DIAERESIS
    table[0x82] = 0x00E9; // LATIN SMALL LETTER E WITH ACUTE
    table[0x83] = 0x00E2; // LATIN SMALL LETTER A WITH CIRCUMFLEX
    table[0x84] = 0x00E4; // LATIN SMALL LETTER A WITH DIAERESIS
    table[0x85] = 0x016F; // LATIN SMALL LETTER U WITH RING ABOVE
    table[0x86] = 0x0107; // LATIN SMALL LETTER C WITH ACUTE
    table[0x87] = 0x00E7; // LATIN SMALL LETTER C WITH CEDILLA
    table[0x88] = 0x0142; // LATIN SMALL LETTER L WITH STROKE
    table[0x89] = 0x00EB; // LATIN SMALL LETTER E WITH DIAERESIS
    table[0x8A] = 0x0150; // LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
    table[0x8B] = 0x0151; // LATIN SMALL LETTER O WITH DOUBLE ACUTE
    table[0x8C] = 0x00EE; // LATIN SMALL LETTER I WITH CIRCUMFLEX
    table[0x8D] = 0x0179; // LATIN CAPITAL LETTER Z WITH ACUTE
    table[0x8E] = 0x00C4; // LATIN CAPITAL LETTER A WITH DIAERESIS
    table[0x8F] = 0x0106; // LATIN CAPITAL LETTER C WITH ACUTE
    table[0x90] = 0x00C9; // LATIN CAPITAL LETTER E WITH ACUTE
    table[0x91] = 0x0139; // LATIN CAPITAL LETTER L WITH ACUTE
    table[0x92] = 0x013A; // LATIN SMALL LETTER L WITH ACUTE
    table[0x93] = 0x00F4; // LATIN SMALL LETTER O WITH CIRCUMFLEX
    table[0x94] = 0x00F6; // LATIN SMALL LETTER O WITH DIAERESIS
    table[0x95] = 0x013D; // LATIN CAPITAL LETTER L WITH CARON
    table[0x96] = 0x013E; // LATIN SMALL LETTER L WITH CARON
    table[0x97] = 0x015A; // LATIN CAPITAL LETTER S WITH ACUTE
    table[0x98] = 0x015B; // LATIN SMALL LETTER S WITH ACUTE
    table[0x99] = 0x00D6; // LATIN CAPITAL LETTER O WITH DIAERESIS
    table[0x9A] = 0x00DC; // LATIN CAPITAL LETTER U WITH DIAERESIS
    table[0x9B] = 0x0164; // LATIN CAPITAL LETTER T WITH CARON
    table[0x9C] = 0x0165; // LATIN SMALL LETTER T WITH CARON
    table[0x9D] = 0x0141; // LATIN CAPITAL LETTER L WITH STROKE
    table[0x9E] = 0x00D7; // MULTIPLICATION SIGN
    table[0x9F] = 0x010D; // LATIN SMALL LETTER C WITH CARON
    // 0xA0-0xAF
    table[0xA0] = 0x00E1; // LATIN SMALL LETTER A WITH ACUTE
    table[0xA1] = 0x00ED; // LATIN SMALL LETTER I WITH ACUTE
    table[0xA2] = 0x00F3; // LATIN SMALL LETTER O WITH ACUTE
    table[0xA3] = 0x00FA; // LATIN SMALL LETTER U WITH ACUTE
    table[0xA4] = 0x0104; // LATIN CAPITAL LETTER A WITH OGONEK
    table[0xA5] = 0x0105; // LATIN SMALL LETTER A WITH OGONEK
    table[0xA6] = 0x017D; // LATIN CAPITAL LETTER Z WITH CARON
    table[0xA7] = 0x017E; // LATIN SMALL LETTER Z WITH CARON
    table[0xA8] = 0x0118; // LATIN CAPITAL LETTER E WITH OGONEK
    table[0xA9] = 0x0119; // LATIN SMALL LETTER E WITH OGONEK
    table[0xAA] = 0x00AC; // NOT SIGN
    table[0xAB] = 0x017A; // LATIN SMALL LETTER Z WITH ACUTE
    table[0xAC] = 0x010C; // LATIN CAPITAL LETTER C WITH CARON
    table[0xAD] = 0x015F; // LATIN SMALL LETTER S WITH CEDILLA
    table[0xAE] = 0x00AB; // LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
    table[0xAF] = 0x00BB; // RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
    // 0xB0-0xDF: Box drawing characters
    table[0xB0] = 0x2591; // LIGHT SHADE
    table[0xB1] = 0x2592; // MEDIUM SHADE
    table[0xB2] = 0x2593; // DARK SHADE
    table[0xB3] = 0x2502; // BOX DRAWINGS LIGHT VERTICAL
    table[0xB4] = 0x2524; // BOX DRAWINGS LIGHT VERTICAL AND LEFT
    table[0xB5] = 0x00C1; // LATIN CAPITAL LETTER A WITH ACUTE
    table[0xB6] = 0x00C2; // LATIN CAPITAL LETTER A WITH CIRCUMFLEX
    table[0xB7] = 0x011A; // LATIN CAPITAL LETTER E WITH CARON
    table[0xB8] = 0x015E; // LATIN CAPITAL LETTER S WITH CEDILLA
    table[0xB9] = 0x2563; // BOX DRAWINGS DOUBLE VERTICAL AND LEFT
    table[0xBA] = 0x2551; // BOX DRAWINGS DOUBLE VERTICAL
    table[0xBB] = 0x2557; // BOX DRAWINGS DOUBLE DOWN AND LEFT
    table[0xBC] = 0x255D; // BOX DRAWINGS DOUBLE UP AND LEFT
    table[0xBD] = 0x017B; // LATIN CAPITAL LETTER Z WITH DOT ABOVE
    table[0xBE] = 0x017C; // LATIN SMALL LETTER Z WITH DOT ABOVE
    table[0xBF] = 0x2510; // BOX DRAWINGS LIGHT DOWN AND LEFT
    table[0xC0] = 0x2514; // BOX DRAWINGS LIGHT UP AND RIGHT
    table[0xC1] = 0x2534; // BOX DRAWINGS LIGHT UP AND HORIZONTAL
    table[0xC2] = 0x252C; // BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
    table[0xC3] = 0x251C; // BOX DRAWINGS LIGHT VERTICAL AND RIGHT
    table[0xC4] = 0x2500; // BOX DRAWINGS LIGHT HORIZONTAL
    table[0xC5] = 0x253C; // BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
    table[0xC6] = 0x0102; // LATIN CAPITAL LETTER A WITH BREVE
    table[0xC7] = 0x0103; // LATIN SMALL LETTER A WITH BREVE
    table[0xC8] = 0x255A; // BOX DRAWINGS DOUBLE UP AND RIGHT
    table[0xC9] = 0x2554; // BOX DRAWINGS DOUBLE DOWN AND RIGHT
    table[0xCA] = 0x2569; // BOX DRAWINGS DOUBLE UP AND HORIZONTAL
    table[0xCB] = 0x2566; // BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
    table[0xCC] = 0x2560; // BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
    table[0xCD] = 0x2550; // BOX DRAWINGS DOUBLE HORIZONTAL
    table[0xCE] = 0x256C; // BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL
    table[0xCF] = 0x00A4; // CURRENCY SIGN
    table[0xD0] = 0x0111; // LATIN SMALL LETTER D WITH STROKE
    table[0xD1] = 0x0110; // LATIN CAPITAL LETTER D WITH STROKE
    table[0xD2] = 0x010E; // LATIN CAPITAL LETTER D WITH CARON
    table[0xD3] = 0x00CB; // LATIN CAPITAL LETTER E WITH DIAERESIS
    table[0xD4] = 0x010F; // LATIN SMALL LETTER D WITH CARON
    table[0xD5] = 0x0147; // LATIN CAPITAL LETTER N WITH CARON
    table[0xD6] = 0x00CD; // LATIN CAPITAL LETTER I WITH ACUTE
    table[0xD7] = 0x00CE; // LATIN CAPITAL LETTER I WITH CIRCUMFLEX
    table[0xD8] = 0x011B; // LATIN SMALL LETTER E WITH CARON
    table[0xD9] = 0x2518; // BOX DRAWINGS LIGHT UP AND LEFT
    table[0xDA] = 0x250C; // BOX DRAWINGS LIGHT DOWN AND RIGHT
    table[0xDB] = 0x2588; // FULL BLOCK
    table[0xDC] = 0x2584; // LOWER HALF BLOCK
    table[0xDD] = 0x0162; // LATIN CAPITAL LETTER T WITH CEDILLA
    table[0xDE] = 0x016E; // LATIN CAPITAL LETTER U WITH RING ABOVE
    table[0xDF] = 0x2580; // UPPER HALF BLOCK
    // 0xE0-0xFF
    table[0xE0] = 0x00D3; // LATIN CAPITAL LETTER O WITH ACUTE
    table[0xE1] = 0x00DF; // LATIN SMALL LETTER SHARP S
    table[0xE2] = 0x00D4; // LATIN CAPITAL LETTER O WITH CIRCUMFLEX
    table[0xE3] = 0x0143; // LATIN CAPITAL LETTER N WITH ACUTE
    table[0xE4] = 0x0144; // LATIN SMALL LETTER N WITH ACUTE
    table[0xE5] = 0x0148; // LATIN SMALL LETTER N WITH CARON
    table[0xE6] = 0x0160; // LATIN CAPITAL LETTER S WITH CARON
    table[0xE7] = 0x0161; // LATIN SMALL LETTER S WITH CARON
    table[0xE8] = 0x0154; // LATIN CAPITAL LETTER R WITH ACUTE
    table[0xE9] = 0x00DA; // LATIN CAPITAL LETTER U WITH ACUTE
    table[0xEA] = 0x0155; // LATIN SMALL LETTER R WITH ACUTE
    table[0xEB] = 0x0170; // LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
    table[0xEC] = 0x00FD; // LATIN SMALL LETTER Y WITH ACUTE
    table[0xED] = 0x00DD; // LATIN CAPITAL LETTER Y WITH ACUTE
    table[0xEE] = 0x0163; // LATIN SMALL LETTER T WITH CEDILLA
    table[0xEF] = 0x00B4; // ACUTE ACCENT
    table[0xF0] = 0x00AD; // SOFT HYPHEN
    table[0xF1] = 0x02DD; // DOUBLE ACUTE ACCENT
    table[0xF2] = 0x02DB; // OGONEK
    table[0xF3] = 0x02C7; // CARON
    table[0xF4] = 0x02D8; // BREVE
    table[0xF5] = 0x00A7; // SECTION SIGN
    table[0xF6] = 0x00F7; // DIVISION SIGN
    table[0xF7] = 0x00B8; // CEDILLA
    table[0xF8] = 0x00B0; // DEGREE SIGN
    table[0xF9] = 0x00A8; // DIAERESIS
    table[0xFA] = 0x02D9; // DOT ABOVE
    table[0xFB] = 0x0171; // LATIN SMALL LETTER U WITH DOUBLE ACUTE
    table[0xFC] = 0x0158; // LATIN CAPITAL LETTER R WITH CARON
    table[0xFD] = 0x0159; // LATIN SMALL LETTER R WITH CARON
    table[0xFE] = 0x25A0; // BLACK SQUARE
    table[0xFF] = 0x00A0; // NO-BREAK SPACE
    break :blk table;
};

const Codec = charmap.CharmapCodec(&decode_table, name);
pub const decode = Codec.decode;
pub const encode = Codec.encode;

test "cp852 decode" {
    const result = try decode(std.testing.allocator, "Hello", .strict);
    defer std.testing.allocator.free(result.output);
    try std.testing.expectEqualStrings("Hello", result.output);
}
