//! CPython source: Lib/encodings/iso8859_16.py
//!
//! South-Eastern European (Romanian, Albanian, Croatian, Slovenian, etc.)
//!
//! Mirrors: CPython Lib/encodings/iso8859_16.py

const std = @import("std");
const charmap = @import("charmap.zig");

pub const name = "iso8859-16";
pub const aliases = [_][]const u8{ "iso-8859-16", "latin10", "l10", "iso_8859_16" };

/// ISO-8859-16 decode table
const decode_table: [256]u21 = blk: {
    var table: [256]u21 = undefined;
    // 0x00-0x9F same as Latin-1
    for (0..0xA0) |i| table[i] = @intCast(i);
    // 0xA0-0xFF
    table[0xA0] = 0x00A0; // NO-BREAK SPACE
    table[0xA1] = 0x0104; // LATIN CAPITAL LETTER A WITH OGONEK
    table[0xA2] = 0x0105; // LATIN SMALL LETTER A WITH OGONEK
    table[0xA3] = 0x0141; // LATIN CAPITAL LETTER L WITH STROKE
    table[0xA4] = 0x20AC; // EURO SIGN
    table[0xA5] = 0x201E; // DOUBLE LOW-9 QUOTATION MARK
    table[0xA6] = 0x0160; // LATIN CAPITAL LETTER S WITH CARON
    table[0xA7] = 0x00A7; // SECTION SIGN
    table[0xA8] = 0x0161; // LATIN SMALL LETTER S WITH CARON
    table[0xA9] = 0x00A9; // COPYRIGHT SIGN
    table[0xAA] = 0x0218; // LATIN CAPITAL LETTER S WITH COMMA BELOW
    table[0xAB] = 0x00AB; // LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
    table[0xAC] = 0x0179; // LATIN CAPITAL LETTER Z WITH ACUTE
    table[0xAD] = 0x00AD; // SOFT HYPHEN
    table[0xAE] = 0x017A; // LATIN SMALL LETTER Z WITH ACUTE
    table[0xAF] = 0x017B; // LATIN CAPITAL LETTER Z WITH DOT ABOVE
    table[0xB0] = 0x00B0; // DEGREE SIGN
    table[0xB1] = 0x00B1; // PLUS-MINUS SIGN
    table[0xB2] = 0x010C; // LATIN CAPITAL LETTER C WITH CARON
    table[0xB3] = 0x0142; // LATIN SMALL LETTER L WITH STROKE
    table[0xB4] = 0x017D; // LATIN CAPITAL LETTER Z WITH CARON
    table[0xB5] = 0x201D; // RIGHT DOUBLE QUOTATION MARK
    table[0xB6] = 0x00B6; // PILCROW SIGN
    table[0xB7] = 0x00B7; // MIDDLE DOT
    table[0xB8] = 0x017E; // LATIN SMALL LETTER Z WITH CARON
    table[0xB9] = 0x010D; // LATIN SMALL LETTER C WITH CARON
    table[0xBA] = 0x0219; // LATIN SMALL LETTER S WITH COMMA BELOW
    table[0xBB] = 0x00BB; // RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
    table[0xBC] = 0x0152; // LATIN CAPITAL LIGATURE OE
    table[0xBD] = 0x0153; // LATIN SMALL LIGATURE OE
    table[0xBE] = 0x0178; // LATIN CAPITAL LETTER Y WITH DIAERESIS
    table[0xBF] = 0x017C; // LATIN SMALL LETTER Z WITH DOT ABOVE
    table[0xC0] = 0x00C0; // LATIN CAPITAL LETTER A WITH GRAVE
    table[0xC1] = 0x00C1; // LATIN CAPITAL LETTER A WITH ACUTE
    table[0xC2] = 0x00C2; // LATIN CAPITAL LETTER A WITH CIRCUMFLEX
    table[0xC3] = 0x0102; // LATIN CAPITAL LETTER A WITH BREVE
    table[0xC4] = 0x00C4; // LATIN CAPITAL LETTER A WITH DIAERESIS
    table[0xC5] = 0x0106; // LATIN CAPITAL LETTER C WITH ACUTE
    table[0xC6] = 0x00C6; // LATIN CAPITAL LETTER AE
    table[0xC7] = 0x00C7; // LATIN CAPITAL LETTER C WITH CEDILLA
    table[0xC8] = 0x00C8; // LATIN CAPITAL LETTER E WITH GRAVE
    table[0xC9] = 0x00C9; // LATIN CAPITAL LETTER E WITH ACUTE
    table[0xCA] = 0x00CA; // LATIN CAPITAL LETTER E WITH CIRCUMFLEX
    table[0xCB] = 0x00CB; // LATIN CAPITAL LETTER E WITH DIAERESIS
    table[0xCC] = 0x00CC; // LATIN CAPITAL LETTER I WITH GRAVE
    table[0xCD] = 0x00CD; // LATIN CAPITAL LETTER I WITH ACUTE
    table[0xCE] = 0x00CE; // LATIN CAPITAL LETTER I WITH CIRCUMFLEX
    table[0xCF] = 0x00CF; // LATIN CAPITAL LETTER I WITH DIAERESIS
    table[0xD0] = 0x0110; // LATIN CAPITAL LETTER D WITH STROKE
    table[0xD1] = 0x0143; // LATIN CAPITAL LETTER N WITH ACUTE
    table[0xD2] = 0x00D2; // LATIN CAPITAL LETTER O WITH GRAVE
    table[0xD3] = 0x00D3; // LATIN CAPITAL LETTER O WITH ACUTE
    table[0xD4] = 0x00D4; // LATIN CAPITAL LETTER O WITH CIRCUMFLEX
    table[0xD5] = 0x0150; // LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
    table[0xD6] = 0x00D6; // LATIN CAPITAL LETTER O WITH DIAERESIS
    table[0xD7] = 0x015A; // LATIN CAPITAL LETTER S WITH ACUTE
    table[0xD8] = 0x0170; // LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
    table[0xD9] = 0x00D9; // LATIN CAPITAL LETTER U WITH GRAVE
    table[0xDA] = 0x00DA; // LATIN CAPITAL LETTER U WITH ACUTE
    table[0xDB] = 0x00DB; // LATIN CAPITAL LETTER U WITH CIRCUMFLEX
    table[0xDC] = 0x00DC; // LATIN CAPITAL LETTER U WITH DIAERESIS
    table[0xDD] = 0x0118; // LATIN CAPITAL LETTER E WITH OGONEK
    table[0xDE] = 0x021A; // LATIN CAPITAL LETTER T WITH COMMA BELOW
    table[0xDF] = 0x00DF; // LATIN SMALL LETTER SHARP S
    table[0xE0] = 0x00E0; // LATIN SMALL LETTER A WITH GRAVE
    table[0xE1] = 0x00E1; // LATIN SMALL LETTER A WITH ACUTE
    table[0xE2] = 0x00E2; // LATIN SMALL LETTER A WITH CIRCUMFLEX
    table[0xE3] = 0x0103; // LATIN SMALL LETTER A WITH BREVE
    table[0xE4] = 0x00E4; // LATIN SMALL LETTER A WITH DIAERESIS
    table[0xE5] = 0x0107; // LATIN SMALL LETTER C WITH ACUTE
    table[0xE6] = 0x00E6; // LATIN SMALL LETTER AE
    table[0xE7] = 0x00E7; // LATIN SMALL LETTER C WITH CEDILLA
    table[0xE8] = 0x00E8; // LATIN SMALL LETTER E WITH GRAVE
    table[0xE9] = 0x00E9; // LATIN SMALL LETTER E WITH ACUTE
    table[0xEA] = 0x00EA; // LATIN SMALL LETTER E WITH CIRCUMFLEX
    table[0xEB] = 0x00EB; // LATIN SMALL LETTER E WITH DIAERESIS
    table[0xEC] = 0x00EC; // LATIN SMALL LETTER I WITH GRAVE
    table[0xED] = 0x00ED; // LATIN SMALL LETTER I WITH ACUTE
    table[0xEE] = 0x00EE; // LATIN SMALL LETTER I WITH CIRCUMFLEX
    table[0xEF] = 0x00EF; // LATIN SMALL LETTER I WITH DIAERESIS
    table[0xF0] = 0x0111; // LATIN SMALL LETTER D WITH STROKE
    table[0xF1] = 0x0144; // LATIN SMALL LETTER N WITH ACUTE
    table[0xF2] = 0x00F2; // LATIN SMALL LETTER O WITH GRAVE
    table[0xF3] = 0x00F3; // LATIN SMALL LETTER O WITH ACUTE
    table[0xF4] = 0x00F4; // LATIN SMALL LETTER O WITH CIRCUMFLEX
    table[0xF5] = 0x0151; // LATIN SMALL LETTER O WITH DOUBLE ACUTE
    table[0xF6] = 0x00F6; // LATIN SMALL LETTER O WITH DIAERESIS
    table[0xF7] = 0x015B; // LATIN SMALL LETTER S WITH ACUTE
    table[0xF8] = 0x0171; // LATIN SMALL LETTER U WITH DOUBLE ACUTE
    table[0xF9] = 0x00F9; // LATIN SMALL LETTER U WITH GRAVE
    table[0xFA] = 0x00FA; // LATIN SMALL LETTER U WITH ACUTE
    table[0xFB] = 0x00FB; // LATIN SMALL LETTER U WITH CIRCUMFLEX
    table[0xFC] = 0x00FC; // LATIN SMALL LETTER U WITH DIAERESIS
    table[0xFD] = 0x0119; // LATIN SMALL LETTER E WITH OGONEK
    table[0xFE] = 0x021B; // LATIN SMALL LETTER T WITH COMMA BELOW
    table[0xFF] = 0x00FF; // LATIN SMALL LETTER Y WITH DIAERESIS
    break :blk table;
};

const Codec = charmap.CharmapCodec(&decode_table, name);
pub const decode = Codec.decode;
pub const encode = Codec.encode;

test "iso8859_16 decode" {
    const result = try decode(std.testing.allocator, "Hello", .strict);
    defer std.testing.allocator.free(result.output);
    try std.testing.expectEqualStrings("Hello", result.output);
}
