//! Auto-generated auto-registrable module names - DO NOT EDIT
//! Generated by: zig build gen-stdlib
//!
//! Modules that can be auto-registered (not in manual registry)

const underscore_misc = @import("auto/underscore_misc.zig");
const c_modules = @import("auto/c_modules.zig");
const c_objects = @import("auto/c_objects.zig");
const underscore_lib = @import("auto/underscore_lib.zig");
const python_modules = @import("auto/python_modules.zig");
const lib_a_to_e = @import("auto/lib_a_to_e.zig");
const lib_f_to_z = @import("auto/lib_f_to_z.zig");
const test_modules = @import("auto/test_modules.zig");

/// Auto-registrable module names
pub const names =
    underscore_misc.names ++
    c_modules.names ++
    c_objects.names ++
    underscore_lib.names ++
    python_modules.names ++
    lib_a_to_e.names ++
    lib_f_to_z.names ++
    test_modules.names;
