//! Auto-generated Lib/ (stdlib) module names - DO NOT EDIT
//! Generated by: zig build gen-stdlib

const underscore = @import("lib/underscore.zig");
const a_to_e = @import("lib/a_to_e.zig");
const f_to_l = @import("lib/f_to_l.zig");
const m_to_r = @import("lib/m_to_r.zig");
const s_to_z = @import("lib/s_to_z.zig");
const test_modules = @import("lib/test_modules.zig");

/// Lib/ stdlib module names
pub const names =
    underscore.names ++
    a_to_e.names ++
    f_to_l.names ++
    m_to_r.names ++
    test_modules.names ++
    s_to_z.names;
