//! Auto-generated Objects/ module names - DO NOT EDIT
//! Generated by: zig build gen-stdlib

/// Objects/ module names
pub const names = [_][]const u8{
    "_objects.boolobject",
    "_objects.complexobject",
    "_objects.dictobject",
    "_objects.fileobject",
    "_objects.floatobject",
    "_objects.intobject",
    "_objects.listobject",
    "_objects.longobject",
    "_objects.object",
    "_objects.stringlib.core",
    "_objects.stringlib.manipulate",
    "_objects.stringlib.pylist",
    "_objects.stringlib.runtime",
    "_objects.stringlib.search",
    "_objects.stringlib.transform",
    "_objects.tupleobject",
    "_objects.unicodeobject",
};
