#!/usr/bin/env python3
"""
Auto-generate package imports from packages/*/package.json

Scans packages/ directory and generates:
  - packages/pkg/src/native_modules_gen.zig  (PyPI skip list)
  - src/codegen/native/packages_gen.zig      (Import mappings for codegen)

Run: python3 scripts/gen_packages.py
"""

import json
import os
from pathlib import Path

PACKAGES_DIR = Path("packages")
OUTPUT_NATIVE_MODULES = Path("packages/pkg/src/native_modules_gen.zig")
OUTPUT_PACKAGES_GEN = Path("src/codegen/native/packages_gen.zig")


def scan_packages():
    """Scan packages/ for package.json files"""
    packages = []

    for pkg_dir in sorted(PACKAGES_DIR.iterdir()):
        if not pkg_dir.is_dir():
            continue
        if pkg_dir.name.startswith('.'):
            continue

        manifest_path = pkg_dir / "package.json"
        if not manifest_path.exists():
            continue

        with open(manifest_path) as f:
            manifest = json.load(f)

        packages.append({
            "name": manifest.get("name", pkg_dir.name),
            "path": str(pkg_dir),
            "root": manifest.get("root", "src/main.zig"),
            "pypi": manifest.get("pypi", []),
            "deps": manifest.get("deps", []),
            "submodules": manifest.get("submodules", {}),
            "optional": manifest.get("optional", False),
        })

    return packages


def generate_native_modules(packages):
    """Generate PyPI skip list"""
    lines = [
        "//! Auto-generated PyPI skip list",
        "//! DO NOT EDIT - Generated by scripts/gen_packages.py",
        "//!",
        "//! Packages with native Zig implementations.",
        "//! Package manager skips downloading these from PyPI.",
        "",
        "const std = @import(\"std\");",
        "",
        "/// PyPI packages with native implementations",
        "pub const native_packages = [_][]const u8{",
    ]

    for pkg in packages:
        for pypi_name in pkg["pypi"]:
            lines.append(f'    "{pypi_name}",')

    lines.extend([
        "};",
        "",
        "/// Check if package has native implementation",
        "pub fn hasNativeImpl(name: []const u8) bool {",
        "    for (native_packages) |pkg| {",
        "        if (std.ascii.eqlIgnoreCase(name, pkg)) return true;",
        "    }",
        "    return false;",
        "}",
        "",
    ])

    return "\n".join(lines)


def generate_packages_gen(packages):
    """Generate import mappings for codegen"""
    lines = [
        "//! Auto-generated package imports",
        "//! DO NOT EDIT - Generated by scripts/gen_packages.py",
        "//!",
        "//! Scanned from packages/*/package.json",
        "",
        "const std = @import(\"std\");",
        "",
        "/// Package info",
        "pub const PackageInfo = struct {",
        "    name: []const u8,",
        "    path: []const u8,",
        "    root: []const u8,",
        "    pypi_names: []const []const u8,",
        "};",
        "",
        "/// All discovered packages",
        "pub const packages = [_]PackageInfo{",
    ]

    for pkg in packages:
        pypi_list = ", ".join(f'"{p}"' for p in pkg["pypi"])
        lines.append(f'    .{{ .name = "{pkg["name"]}", .path = "{pkg["path"]}", .root = "{pkg["root"]}", .pypi_names = &.{{ {pypi_list} }} }},')

    lines.extend([
        "};",
        "",
        "/// Lookup package by name",
        "pub fn getPackage(name: []const u8) ?PackageInfo {",
        "    for (packages) |pkg| {",
        "        if (std.mem.eql(u8, pkg.name, name)) return pkg;",
        "    }",
        "    return null;",
        "}",
        "",
        "/// Lookup package by PyPI name",
        "pub fn getPackageByPypi(pypi_name: []const u8) ?PackageInfo {",
        "    for (packages) |pkg| {",
        "        for (pkg.pypi_names) |name| {",
        "            if (std.ascii.eqlIgnoreCase(name, pypi_name)) return pkg;",
        "        }",
        "    }",
        "    return null;",
        "}",
        "",
    ])

    return "\n".join(lines)


def main():
    packages = scan_packages()

    # Generate native_modules_gen.zig
    native_modules_content = generate_native_modules(packages)
    OUTPUT_NATIVE_MODULES.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_NATIVE_MODULES.write_text(native_modules_content)

    # Generate packages_gen.zig
    packages_gen_content = generate_packages_gen(packages)
    OUTPUT_PACKAGES_GEN.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PACKAGES_GEN.write_text(packages_gen_content)

    # Summary
    pypi_count = sum(len(p["pypi"]) for p in packages)
    print(f"Generated package imports:")
    print(f"  - Packages: {len(packages)}")
    print(f"  - PyPI overrides: {pypi_count}")
    print(f"  - {OUTPUT_NATIVE_MODULES}")
    print(f"  - {OUTPUT_PACKAGES_GEN}")


if __name__ == "__main__":
    main()
