/**
 * TypeScript definitions for math WASM module
 * Auto-generated by metal0
 *
 * Usage:
 *   import { load } from '@metal0/wasm-runtime';
 *   import type { Module } from './math';
 *   const mod = await load<Module>('./math.wasm');
 */

export interface Module {
  add(a: number, b: number): number;
  multiply(x: number, y: number): number;
  square(n: number): number;
  max_of(a: number, b: number): number;
  abs_val(n: number): number;
}
