/// @logic_table class code generation
///
/// The @logic_table decorator marks a class for special output format.
/// All Python syntax is handled by metal0's existing codegen infrastructure.
///
/// Example input:
/// ```python
/// @logic_table
/// class VectorOps:
///     def cosine_sim(self):
///         dot = sum(query.embedding * docs.embedding)
///         return dot / (norm(query.embedding) * norm(docs.embedding))
/// ```
///
/// Generated output:
/// ```zig
/// pub const VectorOps = struct {
///     pub const __logic_table__ = true;
///     pub fn cosine_sim(...) { ... }  // Generated by existing genFunctionDef
///     pub const methods = [_][]const u8{ "cosine_sim" };
/// };
/// ```

const std = @import("std");
const ast = @import("analysis.ast");
const NativeCodegen = @import("main.zig").NativeCodegen;
const CodegenError = @import("main.zig").CodegenError;
const function_generators = @import("statements/functions/generators.zig");

/// Check if a class has @logic_table decorator
pub fn hasLogicTableDecorator(class: ast.Node.ClassDef) bool {
    for (class.decorators) |decorator| {
        // Check for simple name: @logic_table
        if (decorator == .name) {
            if (std.mem.eql(u8, decorator.name.id, "logic_table")) {
                return true;
            }
        }
        // Check for attribute access: @module.logic_table
        if (decorator == .attribute) {
            if (std.mem.eql(u8, decorator.attribute.attr, "logic_table")) {
                return true;
            }
        }
        // Check for call: @logic_table()
        if (decorator == .call) {
            if (decorator.call.func.* == .name) {
                if (std.mem.eql(u8, decorator.call.func.name.id, "logic_table")) {
                    return true;
                }
            }
        }
    }
    return false;
}

/// Generate @logic_table class as a Zig struct
/// Uses existing metal0 codegen for method bodies - no custom expression handling
pub fn genLogicTableClass(self: *NativeCodegen, class: ast.Node.ClassDef) CodegenError!void {
    const allocator = self.allocator;

    // Emit struct definition
    try self.emitIndent();
    try self.emit("pub const ");
    try self.emit(class.name);
    try self.emit(" = struct {\n");

    self.indent_level += 1;

    // Emit __logic_table__ marker
    try self.emitIndent();
    try self.emit("pub const __logic_table__ = true;\n\n");

    // Collect method names for the methods array
    var method_names: std.ArrayListUnmanaged([]const u8) = .{};
    defer method_names.deinit(allocator);

    // Generate methods using existing codegen
    for (class.body) |stmt| {
        if (stmt == .function_def) {
            const method = stmt.function_def;

            // Skip __init__ and dunder methods
            if (std.mem.startsWith(u8, method.name, "__")) continue;

            try method_names.append(allocator, method.name);

            // Use existing function generator - handles ALL Python syntax
            try function_generators.genFunctionDef(self, method);
        }
    }

    // Emit methods registry
    try self.emitIndent();
    try self.emit("pub const methods = [_][]const u8{\n");
    self.indent_level += 1;
    for (method_names.items) |name| {
        try self.emitIndent();
        try self.emitFmt("\"{s}\",\n", .{name});
    }
    self.indent_level -= 1;
    try self.emitIndent();
    try self.emit("};\n");

    self.indent_level -= 1;
    try self.emitIndent();
    try self.emit("};\n");
}

test "hasLogicTableDecorator" {
    // Test with simple decorator
    const class1 = ast.Node.ClassDef{
        .name = "Test",
        .bases = &[_][]const u8{},
        .body = &[_]ast.Node{},
        .decorators = &[_]ast.Node{
            .{ .name = .{ .id = "logic_table" } },
        },
    };
    try std.testing.expect(hasLogicTableDecorator(class1));

    // Test without decorator
    const class2 = ast.Node.ClassDef{
        .name = "Test",
        .bases = &[_][]const u8{},
        .body = &[_]ast.Node{},
        .decorators = &[_]ast.Node{},
    };
    try std.testing.expect(!hasLogicTableDecorator(class2));
}
