/// @logic_table class code generation
///
/// The @logic_table decorator marks a class for special output format.
/// All Python syntax is handled by metal0's existing codegen infrastructure.
///
/// Example input:
/// ```python
/// @logic_table
/// class VectorOps:
///     def cosine_sim(self):
///         dot = sum(query.embedding * docs.embedding)
///         return dot / (norm(query.embedding) * norm(docs.embedding))
/// ```
///
/// Generated output:
/// ```zig
/// pub const VectorOps = struct {
///     pub const __logic_table__ = true;
///     pub fn cosine_sim(...) { ... }  // Generated by existing genFunctionDef
///     pub const methods = [_][]const u8{ "cosine_sim" };
/// };
/// // C-callable wrappers for external linking
/// export fn VectorOps_cosine_sim(...) callconv(.C) f64 {
///     return VectorOps.cosine_sim(...);
/// }
/// ```

const std = @import("std");
const ast = @import("analysis.ast");
const NativeCodegen = @import("main.zig").NativeCodegen;
const CodegenError = @import("main.zig").CodegenError;
const function_generators = @import("statements/functions/generators.zig");

/// Check if a class has @logic_table decorator
pub fn hasLogicTableDecorator(class: ast.Node.ClassDef) bool {
    for (class.decorators) |decorator| {
        // Check for simple name: @logic_table
        if (decorator == .name) {
            if (std.mem.eql(u8, decorator.name.id, "logic_table")) {
                return true;
            }
        }
        // Check for attribute access: @module.logic_table
        if (decorator == .attribute) {
            if (std.mem.eql(u8, decorator.attribute.attr, "logic_table")) {
                return true;
            }
        }
        // Check for call: @logic_table()
        if (decorator == .call) {
            if (decorator.call.func.* == .name) {
                if (std.mem.eql(u8, decorator.call.func.name.id, "logic_table")) {
                    return true;
                }
            }
        }
    }
    return false;
}

/// Method info for generating export wrappers
const MethodInfo = struct {
    name: []const u8,
    func: ast.Node.FunctionDef,
};

/// Generate @logic_table class as a Zig struct
/// Uses existing metal0 codegen for method bodies - no custom expression handling
pub fn genLogicTableClass(self: *NativeCodegen, class: ast.Node.ClassDef) CodegenError!void {
    const allocator = self.allocator;

    // Emit struct definition
    try self.emitIndent();
    try self.emit("pub const ");
    try self.emit(class.name);
    try self.emit(" = struct {\n");

    self.indent_level += 1;

    // Emit __logic_table__ marker
    try self.emitIndent();
    try self.emit("pub const __logic_table__ = true;\n\n");

    // Set flag so genFunctionSignature emits 'pub fn'
    self.in_logic_table_class = true;
    defer self.in_logic_table_class = false;

    // Collect method info for the methods array and export wrappers
    var methods: std.ArrayListUnmanaged(MethodInfo) = .{};
    defer methods.deinit(allocator);

    // Generate methods using existing codegen
    for (class.body) |stmt| {
        if (stmt == .function_def) {
            const method = stmt.function_def;

            // Skip __init__ and dunder methods
            if (std.mem.startsWith(u8, method.name, "__")) continue;

            try methods.append(allocator, .{ .name = method.name, .func = method });

            // Use existing function generator - handles ALL Python syntax
            try function_generators.genFunctionDef(self, method);
        }
    }

    // Emit methods registry
    try self.emitIndent();
    try self.emit("pub const methods = [_][]const u8{\n");
    self.indent_level += 1;
    for (methods.items) |m| {
        try self.emitIndent();
        try self.emitFmt("\"{s}\",\n", .{m.name});
    }
    self.indent_level -= 1;
    try self.emitIndent();
    try self.emit("};\n");

    self.indent_level -= 1;
    try self.emitIndent();
    try self.emit("};\n\n");

    // Generate C-callable export wrappers at module level
    // These are free functions with export linkage that call the struct methods
    try self.emit("// __logic_table_exports_begin__\n");
    for (methods.items) |m| {
        try genExportWrapper(self, class.name, m.name, m.func);
    }
    try self.emit("// __logic_table_exports_end__\n");
}

/// Generate a C-callable export wrapper for a struct method
/// This allows the method to be called from C/external code via dlsym
fn genExportWrapper(self: *NativeCodegen, class_name: []const u8, method_name: []const u8, func: ast.Node.FunctionDef) CodegenError!void {
    // Export wrapper signature: export fn ClassName_methodName(args...) callconv(.C) ReturnType
    try self.emitFmt("export fn {s}_{s}(", .{ class_name, method_name });

    // Generate parameters (skip 'self' which is the first parameter)
    var param_count: usize = 0;
    for (func.args) |arg| {
        // Skip 'self' parameter
        if (std.mem.eql(u8, arg.name, "self")) continue;

        if (param_count > 0) try self.emit(", ");

        // For simplicity, use f64 for numeric types and [*]f64 for arrays
        // This provides a C-compatible ABI
        try self.emitFmt("{s}: ", .{arg.name});
        if (arg.type_annotation) |type_name| {
            if (std.mem.eql(u8, type_name, "float")) {
                try self.emit("f64");
            } else if (std.mem.eql(u8, type_name, "int")) {
                try self.emit("i64");
            } else if (std.mem.eql(u8, type_name, "list") or std.mem.startsWith(u8, type_name, "list[")) {
                // list or list[float] -> [*]f64
                try self.emit("[*]f64");
            } else {
                try self.emit("*anyopaque"); // Generic pointer for unknown types
            }
        } else {
            // No annotation - assume f64 for numeric compatibility
            try self.emit("f64");
        }
        param_count += 1;
    }

    // If there were array parameters, add a length parameter
    var has_array_param = false;
    for (func.args) |arg| {
        if (std.mem.eql(u8, arg.name, "self")) continue;
        if (arg.type_annotation) |type_name| {
            if (std.mem.eql(u8, type_name, "list") or std.mem.startsWith(u8, type_name, "list[")) {
                has_array_param = true;
                break;
            }
        }
    }
    if (has_array_param) {
        if (param_count > 0) try self.emit(", ");
        try self.emit("len: usize");
    }

    // Return type - use .c for C calling convention
    try self.emit(") callconv(.c) ");

    // Determine return type from annotation
    if (func.return_type) |ret_type| {
        if (std.mem.eql(u8, ret_type, "float")) {
            try self.emit("f64");
        } else if (std.mem.eql(u8, ret_type, "int")) {
            try self.emit("i64");
        } else {
            try self.emit("f64"); // Default to f64
        }
    } else {
        try self.emit("f64"); // Default return type
    }

    try self.emit(" {\n");
    self.indent_level += 1;

    // Generate call to struct method
    // The struct method has signature: fn(self, args...)
    // For static functions without self state, pass undefined for self
    try self.emitIndent();
    try self.emitFmt("return {s}.{s}(undefined", .{ class_name, method_name });

    // Forward parameters
    for (func.args) |arg| {
        if (std.mem.eql(u8, arg.name, "self")) continue;

        // Wrap pointer parameters in slices using length
        if (arg.type_annotation) |type_name| {
            if (std.mem.eql(u8, type_name, "list") or std.mem.startsWith(u8, type_name, "list[")) {
                try self.emitFmt(", {s}[0..len]", .{arg.name});
            } else {
                try self.emitFmt(", {s}", .{arg.name});
            }
        } else {
            try self.emitFmt(", {s}", .{arg.name});
        }
    }

    try self.emit(");\n");

    self.indent_level -= 1;
    try self.emitIndent();
    try self.emit("}\n\n");
}

test "hasLogicTableDecorator" {
    // Test with simple decorator
    const class1 = ast.Node.ClassDef{
        .name = "Test",
        .bases = &[_][]const u8{},
        .body = &[_]ast.Node{},
        .decorators = &[_]ast.Node{
            .{ .name = .{ .id = "logic_table" } },
        },
    };
    try std.testing.expect(hasLogicTableDecorator(class1));

    // Test without decorator
    const class2 = ast.Node.ClassDef{
        .name = "Test",
        .bases = &[_][]const u8{},
        .body = &[_]ast.Node{},
        .decorators = &[_]ast.Node{},
    };
    try std.testing.expect(!hasLogicTableDecorator(class2));
}
