//! Auto-generated package imports
//! DO NOT EDIT - Generated by scripts/gen_packages.py
//!
//! Scanned from packages/*/package.json

const std = @import("std");

/// Package info
pub const PackageInfo = struct {
    name: []const u8,
    path: []const u8,
    root: []const u8,
    pypi_names: []const []const u8,
};

/// All discovered packages
pub const packages = [_]PackageInfo{
    .{ .name = "bigint", .path = "packages/bigint", .root = "src/bigint.zig", .pypi_names = &.{  } },
    .{ .name = "collections", .path = "packages/collections", .root = "collections.zig", .pypi_names = &.{  } },
    .{ .name = "ds", .path = "packages/ds", .root = "src/ds.zig", .pypi_names = &.{  } },
    .{ .name = "glob", .path = "packages/glob", .root = "src/glob.zig", .pypi_names = &.{  } },
    .{ .name = "http", .path = "packages/http", .root = "../shared/http/h2/h2.zig", .pypi_names = &.{ "requests", "httpx", "urllib3", "aiohttp" } },
    .{ .name = "pkg", .path = "packages/pkg", .root = "src/pkg.zig", .pypi_names = &.{  } },
    .{ .name = "regex", .path = "packages/regex", .root = "src/pyregex/regex.zig", .pypi_names = &.{ "regex" } },
    .{ .name = "shared", .path = "packages/shared", .root = "json/json.zig", .pypi_names = &.{ "ujson", "orjson", "simplejson" } },
    .{ .name = "threading", .path = "packages/threading", .root = "src/ThreadPool.zig", .pypi_names = &.{  } },
    .{ .name = "tokenizer", .path = "packages/tokenizer", .root = "src/tokenizer.zig", .pypi_names = &.{ "tiktoken", "tokenizers" } },
    .{ .name = "@metal0/wasm-runtime", .path = "packages/wasm-runtime", .root = "src/main.zig", .pypi_names = &.{  } },
    .{ .name = "wasmedge", .path = "packages/wasmedge", .root = "wasmedge.zig", .pypi_names = &.{  } },
    .{ .name = "websocket", .path = "packages/websocket", .root = "src/main.zig", .pypi_names = &.{ "websockets", "websocket-client" } },
};

/// Lookup package by name
pub fn getPackage(name: []const u8) ?PackageInfo {
    for (packages) |pkg| {
        if (std.mem.eql(u8, pkg.name, name)) return pkg;
    }
    return null;
}

/// Lookup package by PyPI name
pub fn getPackageByPypi(pypi_name: []const u8) ?PackageInfo {
    for (packages) |pkg| {
        for (pkg.pypi_names) |name| {
            if (std.ascii.eqlIgnoreCase(name, pypi_name)) return pkg;
        }
    }
    return null;
}
