//! Auto-generated stdlib module list - DO NOT EDIT
//! Generated by: zig build gen-stdlib
//!
//! Sources:
//!   - packages/runtime/src/Lib/*.zig (stdlib)
//!   - packages/runtime/src/Modules/*.zig (C extension modules)
//!   - packages/runtime/src/Objects/*.zig (object implementations)
//!   - packages/runtime/src/Python/*.zig (interpreter internals)
//!   - packages/c_interop/src/objects/*.zig (CPython object mirrors)
//!   - packages/c_interop/src/modules/*.zig (CPython module mirrors)

const std = @import("std");

// Import split module name lists
const lib_modules = @import("module_names/lib_modules.zig");
const objects_modules = @import("module_names/objects_modules.zig");
const python_modules = @import("module_names/python_modules.zig");
const c_modules = @import("module_names/c_modules.zig");
const c_objects = @import("module_names/c_objects.zig");
const auto_registrable = @import("module_names/auto_registrable.zig");

/// List of all discovered stdlib module files
/// Combined from Lib/, Objects/, Python/, and c_interop/
pub const stdlib_module_names =
    lib_modules.names ++
    objects_modules.names ++
    python_modules.names ++
    c_modules.names ++
    c_objects.names;

/// Number of discovered stdlib modules
pub const stdlib_module_count: usize = stdlib_module_names.len;

/// StaticStringMap for O(1) module lookup (DCE-friendly, comptime-only)
/// This replaces the linear scan with a comptime-generated hash table
pub const module_map = std.StaticStringMap(void).initComptime(blk: {
    @setEvalBranchQuota(20000);
    var entries: [stdlib_module_names.len]struct { []const u8, void } = undefined;
    for (stdlib_module_names, 0..) |name, i| {
        entries[i] = .{ name, {} };
    }
    break :blk entries[0..];
});

/// Check if a module name exists in stdlib (O(1) lookup)
pub fn hasModule(name: []const u8) bool {
    return module_map.has(name);
}

/// Modules that can be auto-registered (not in manual registry)
pub const auto_registrable_modules = auto_registrable.names;

/// Number of auto-registrable modules
pub const auto_registrable_count: usize = auto_registrable.names.len;
