/// Python winreg module - Windows registry access
/// MIGRATED TO ZIGBUILDER
/// DRY: Uses h.c(), h.I64() factories for constants
const std = @import("std");
const h = @import("mod_helper.zig");

pub const Funcs = std.StaticStringMap(h.H).initComptime(.{
    // Registry key operations
    .{ "close_key", h.c("{}") },
    .{ "connect_registry", h.c("null") },
    .{ "create_key", h.c("null") },
    .{ "create_key_ex", h.c("null") },
    .{ "delete_key", h.c("{}") },
    .{ "delete_key_ex", h.c("{}") },
    .{ "delete_value", h.c("{}") },
    .{ "enum_key", h.c("\"\"") },
    .{ "enum_value", h.c(".{ \"\", null, 0 }") },
    .{ "expand_environment_strings", h.c("\"\"") },
    .{ "flush_key", h.c("{}") },
    .{ "load_key", h.c("{}") },
    .{ "open_key", h.c("null") },
    .{ "open_key_ex", h.c("null") },
    .{ "query_info_key", h.c(".{ 0, 0, 0 }") },
    .{ "query_value", h.c("\"\"") },
    .{ "query_value_ex", h.c(".{ null, 0 }") },
    .{ "save_key", h.c("{}") },
    .{ "set_value", h.c("{}") },
    .{ "set_value_ex", h.c("{}") },
    .{ "disable_reflection_key", h.c("{}") },
    .{ "enable_reflection_key", h.c("{}") },
    .{ "query_reflection_key", h.c("false") },
    // HKEY_* predefined keys
    .{ "h_k_e_y__c_l_a_s_s_e_s__r_o_o_t", h.c("0x80000000") },
    .{ "h_k_e_y__c_u_r_r_e_n_t__u_s_e_r", h.c("0x80000001") },
    .{ "h_k_e_y__l_o_c_a_l__m_a_c_h_i_n_e", h.c("0x80000002") },
    .{ "h_k_e_y__u_s_e_r_s", h.c("0x80000003") },
    .{ "h_k_e_y__p_e_r_f_o_r_m_a_n_c_e__d_a_t_a", h.c("0x80000004") },
    .{ "h_k_e_y__c_u_r_r_e_n_t__c_o_n_f_i_g", h.c("0x80000005") },
    .{ "h_k_e_y__d_y_n__d_a_t_a", h.c("0x80000006") },
    // KEY_* access rights
    .{ "k_e_y__a_l_l__a_c_c_e_s_s", h.c("0xF003F") },
    .{ "k_e_y__w_r_i_t_e", h.c("0x20006") },
    .{ "k_e_y__r_e_a_d", h.c("0x20019") },
    .{ "k_e_y__e_x_e_c_u_t_e", h.c("0x20019") },
    .{ "k_e_y__q_u_e_r_y__v_a_l_u_e", h.c("0x0001") },
    .{ "k_e_y__s_e_t__v_a_l_u_e", h.c("0x0002") },
    .{ "k_e_y__c_r_e_a_t_e__s_u_b__k_e_y", h.c("0x0004") },
    .{ "k_e_y__e_n_u_m_e_r_a_t_e__s_u_b__k_e_y_s", h.c("0x0008") },
    .{ "k_e_y__n_o_t_i_f_y", h.c("0x0010") },
    .{ "k_e_y__c_r_e_a_t_e__l_i_n_k", h.c("0x0020") },
    .{ "k_e_y__w_o_w64_64_k_e_y", h.c("0x0100") },
    .{ "k_e_y__w_o_w64_32_k_e_y", h.c("0x0200") },
    // REG_* value types
    .{ "r_e_g__n_o_n_e", h.I64(0) },
    .{ "r_e_g__s_z", h.I64(1) },
    .{ "r_e_g__e_x_p_a_n_d__s_z", h.I64(2) },
    .{ "r_e_g__b_i_n_a_r_y", h.I64(3) },
    .{ "r_e_g__d_w_o_r_d", h.I64(4) },
    .{ "r_e_g__d_w_o_r_d__l_i_t_t_l_e__e_n_d_i_a_n", h.I64(4) },
    .{ "r_e_g__d_w_o_r_d__b_i_g__e_n_d_i_a_n", h.I64(5) },
    .{ "r_e_g__l_i_n_k", h.I64(6) },
    .{ "r_e_g__m_u_l_t_i__s_z", h.I64(7) },
    .{ "r_e_g__r_e_s_o_u_r_c_e__l_i_s_t", h.I64(8) },
    .{ "r_e_g__f_u_l_l__r_e_s_o_u_r_c_e__d_e_s_c_r_i_p_t_o_r", h.I64(9) },
    .{ "r_e_g__r_e_s_o_u_r_c_e__r_e_q_u_i_r_e_m_e_n_t_s__l_i_s_t", h.I64(10) },
    .{ "r_e_g__q_w_o_r_d", h.I64(11) },
    .{ "r_e_g__q_w_o_r_d__l_i_t_t_l_e__e_n_d_i_a_n", h.I64(11) },
});
